// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLModelIntent2
{
    public partial class MLModelIntent1
    {
        /// <summary>
        /// model input class for MLModelIntent1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Utterances")]
            public string Utterances { get; set; }

            [ColumnName(@"Intent")]
            public string Intent { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModelIntent1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Utterances")]
            public float[] Utterances { get; set; }

            [ColumnName(@"Intent")]
            public uint Intent { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion


        private static string MLNetModelPath = "C:\\skole\\eux\\H5\\Machine_Learing\\ChatBot\\MLModelIntent2\\MLModelIntent1.zip";

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
