
// This file was auto-generated by ML.NET Model Builder. 

using MLModelIntent1;

// Create single instance of sample data from first line of dataset for model input
MLModelIntent1.ModelInput sampleData = new MLModelIntent1.ModelInput()
{
    Utterances = @"all about you",
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModelIntent1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Intent with predicted Intent from sample data...\n\n");


Console.WriteLine($"Utterances: {@"all about you"}");
Console.WriteLine($"Intent: {@"smalltalk_agent_acquaintance"}");


Console.WriteLine($"\n\nPredicted Intent: {predictionResult.PredictedLabel}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

